### ISSUE TITLE
Ranking 沒有更新

### ISSUE THREAD

**Issue by alexypdu** [WeiChiaChang/js-pop-quiz#5]
透過 GitHub 登入，但玩了幾次後都沒有看到排行榜更新，Google Chrome 的 console 跟 network 也沒有任何動靜。

**Comment by WeiChiaChang** [comment]
Hello @alexypdu 

因為目前的機制是使用 GitHub 帳號登入之後只會接受第一次的成績，
也就是說一但資料庫有記錄之後，之後的成績就算拿滿分都會忽略，
剛剛看 Firebase 後台的確是有看到你的記錄

<img width="645" alt="螢幕快照 2020-03-21 上午11 30 14" src="https://user-images.githubusercontent.com/13506626/77218544-5fb93c00-6b67-11ea-92cd-21c1ded63c1a.png">

加上當前 Ranking 資料設定是只會抓前十名的，
所以才會造成沒有更新的感覺，
拍謝是我沒有在文件裡面寫清楚ＱＱ

感謝你的 feedback 🙏

**Comment by alexypdu** [comment]
了解了，thanks！
